name: brandoid
favicon: null
layout_spectrum: 0.8673006063327193
typography_spectrum: 0.2161768979858607
title: Alessandro Brandolisio Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3393506589345634
  lightness: 0.8239438715390861
  saturation: 0.7461814212147146
  rhythmicContrast: 0.994940317235887
purpose: []
