name: brandoid
favicon: null
layout_spectrum: 0
typography_spectrum: 0.54558
title: Alessandro Brandolisio Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffffd'
    - '#c71326'
    - '#8f6d6e'
    - '#ff9478'
    - '#e05341'
  brandStrength: 0.875
  lightness: 0.8125
  saturation: 1
  rhythmicContrast: 0
purpose: []
